'use strict';

/**
 * Explicit dual-database ownership contract.
 *
 * MariaDB is the default primary. Firestore is the secondary / operational
 * fallback. Ownership is per-entity, never implied by whichever adapter a
 * route happens to call.
 *
 * Write modes:
 *   SINGLE_OWNER  — only the authoritative engine accepts writes; the other
 *                   is updated asynchronously via the durable outbox.
 *   MULTI_WRITER  — both engines may accept writes during failover; conflicts
 *                   are resolved by monotonic revision + mutation sequence.
 *
 * Deletion: tombstone + mutation event. A missing document is NEVER treated
 * as "recreate me".
 */

const ENTITIES = Object.freeze({
    user: {
        entity: 'user',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        dateFields: ['membershipEnds', 'lastPaymentDate', 'createdAt', 'updatedAt', 'created_at', 'updated_at'],
        tombstoneOnDelete: true,
        notes: 'Canonical user id is the Firebase Auth UID. Membership/subscription fields live on the user record.',
    },
    membership: {
        entity: 'membership',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        embeddedIn: 'user',
        dateFields: ['membershipEnds', 'membershipStarts'],
        tombstoneOnDelete: false,
        notes: 'Not a standalone table. Fields membership, membershipEnds, paymentStatus on users.',
    },
    subscription: {
        entity: 'subscription',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        dateFields: ['created_at', 'updated_at'],
        tombstoneOnDelete: true,
        notes: 'subscriptions table + user.membership fields. Payment orders are the source of activation.',
    },
    payment_order: {
        entity: 'payment_order',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'STRONG_ON_PRIMARY',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        dateFields: ['membershipEnds', 'activatedAt', 'reversedAt', 'createdAt', 'updatedAt'],
        tombstoneOnDelete: true,
        notes: 'Payment activation is strongly consistent on the write-authority engine.',
    },
    resume: {
        entity: 'resume',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        dateFields: ['created_at', 'updated_at', 'createdAt', 'updatedAt', 'publishedAt'],
        tombstoneOnDelete: true,
        notes: 'Canonical resume id is application-generated, shared across engines.',
    },
    portfolio: {
        entity: 'portfolio',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        dateFields: ['created_at', 'updated_at', 'createdAt', 'updatedAt'],
        tombstoneOnDelete: true,
    },
    cover: {
        entity: 'cover',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        dateFields: ['created_at', 'updated_at', 'createdAt', 'updatedAt'],
        tombstoneOnDelete: true,
    },
    settings: {
        entity: 'settings',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'SINGLE_OWNER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'category',
        versionField: 'revision',
        dateFields: ['updatedAt', 'updated_at'],
        tombstoneOnDelete: false,
        notes: 'Platform configuration. Writes follow the configured primary.',
    },
    role: {
        entity: 'role',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'SINGLE_OWNER',
        consistency: 'STRONG_ON_PRIMARY',
        conflict: 'ORIGIN_PRIMARY',
        idField: 'id',
        versionField: 'revision',
        embeddedIn: 'user',
        dateFields: [],
        tombstoneOnDelete: false,
        notes: 'Role lives on users.role plus Firebase custom claims (identity plane).',
    },
    permission: {
        entity: 'permission',
        mariadb: false,
        firestore: false,
        authoritative: 'code',
        syncDirection: 'NONE',
        writeMode: 'SINGLE_OWNER',
        consistency: 'STRONG',
        conflict: 'N/A',
        idField: 'code',
        versionField: null,
        dateFields: [],
        tombstoneOnDelete: false,
        notes: 'RBAC permission matrix is code-defined in backend/security/auth.js, not a database entity.',
    },
    job: {
        entity: 'job',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        dateFields: ['created_at', 'updated_at', 'expires_at', 'deadline'],
        tombstoneOnDelete: true,
    },
    application: {
        entity: 'application',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        dateFields: ['created_at', 'updated_at'],
        tombstoneOnDelete: true,
    },
    blog: {
        entity: 'blog',
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        dateFields: ['created_at', 'updated_at', 'published_at'],
        tombstoneOnDelete: true,
    },
});

function getOwnership(entityType) {
    const key = String(entityType || '').trim().toLowerCase();
    const aliases = {
        users: 'user',
        resumes: 'resume',
        portfolios: 'portfolio',
        covers: 'cover',
        jobs: 'job',
        applications: 'application',
        memberships: 'membership',
        subscriptions: 'subscription',
        payment_orders: 'payment_order',
        system_settings: 'settings',
        roles: 'role',
        permissions: 'permission',
        custom_pages: 'settings',
    };
    const resolved = aliases[key] || key;
    return ENTITIES[resolved] || {
        entity: resolved,
        mariadb: true,
        firestore: true,
        authoritative: 'mariadb',
        syncDirection: 'BIDIRECTIONAL',
        writeMode: 'MULTI_WRITER',
        consistency: 'EVENTUAL',
        conflict: 'VERSION',
        idField: 'id',
        versionField: 'revision',
        dateFields: [],
        tombstoneOnDelete: true,
        notes: 'Default contract for unlisted entities.',
    };
}

function ownershipMatrix() {
    return Object.values(ENTITIES).map((row) => ({
        Entity: row.entity,
        MariaDB: row.mariadb ? 'Yes' : 'No',
        Firestore: row.firestore ? 'Yes' : 'No',
        AuthoritativeSource: row.authoritative,
        SyncDirection: row.syncDirection,
        WriteMode: row.writeMode,
        Conflict: row.conflict,
        Deletion: row.tombstoneOnDelete ? 'tombstone' : 'none',
    }));
}

module.exports = {
    ENTITIES,
    getOwnership,
    ownershipMatrix,
};
