/**
 * Smart Hybrid Resume Engine — Theme & Design Token Presets
 * 
 * Maps all 51 template IDs (Cv1 to Cv51) into curated, enterprise-grade
 * design configurations with balanced archetypes, harmonious color palettes,
 * modern typography, and responsive skill presentation.
 */

export const ARCHETYPES = {
  MODERN_SPLIT: 'modern-split',       // Left sidebar (32-35%), crisp main flow (65-68%)
  EXECUTIVE_BANNER: 'executive-banner', // Full-width header banner, structured 2-col below
  MINIMAL_ATS: 'minimal-ats',         // Single column, 100% ATS-optimized, classic elegance
  TECH_GRID: 'tech-grid',             // Tech badges, repository links, compact timeline
  COMPACT_EURO: 'compact-euro',       // Europass / Academic timeline with date gutter
};

export const SKILL_VARIANTS = {
  PILLS: 'pills',                     // Compact multi-column pill wrap (best for 10+ skills)
  BADGES: 'badges',                   // Outlined tech tags with subtle background
  BARS: 'bars',                       // Horizontal proficiency meters
  DOTS: 'dots',                       // 5-dot rating indicator
  INLINE: 'inline',                   // Inline comma / bullet separated list
};

/**
 * 51 Curated Theme Presets
 */
export const THEME_PRESETS = {
  // ── Modern Split Presets (Cv1, Cv2, Cv3, Cv7, Cv9, Cv20, Cv24, Cv27, Cv47, Cv48, Cv50) ──
  Cv1: {
    name: 'Metropolitan Navy',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#1e3a8a',
    secondary: '#3b82f6',
    sidebarBg: '#f8fafc',
    sidebarText: '#1e293b',
    headerBg: 'transparent',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv2: {
    name: 'Nordic Slate',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#0f172a',
    secondary: '#0ea5e9',
    sidebarBg: '#f1f5f9',
    sidebarText: '#334155',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '33%',
    badgeRadius: '4px',
    timelineStyle: 'subtle-line',
  },
  Cv3: {
    name: 'Emerald Executive',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#065f46',
    secondary: '#10b981',
    sidebarBg: '#f0fdf4',
    sidebarText: '#166534',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv4: {
    name: 'Harvard Classic ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#111827',
    secondary: '#4b5563',
    font: "'Merriweather', Georgia, serif",
    skillVariant: SKILL_VARIANTS.INLINE,
    dividerStyle: 'solid-thin',
    density: 'standard',
  },
  Cv5: {
    name: 'Stanford Clean ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#1e293b',
    secondary: '#64748b',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    dividerStyle: 'accent-left',
    density: 'standard',
  },
  Cv6: {
    name: 'Wall Street Modern',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#0f172a',
    secondary: '#2563eb',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    dividerStyle: 'double-line',
    density: 'compact',
  },
  Cv7: {
    name: 'Sapphire Modern Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#1d4ed8',
    secondary: '#60a5fa',
    sidebarBg: '#eff6ff',
    sidebarText: '#1e3a8a',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '8px',
    timelineStyle: 'modern-node',
  },
  Cv8: {
    name: 'Crown Executive Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#1e293b',
    secondary: '#3b82f6',
    headerBg: 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)',
    headerText: '#ffffff',
    font: "'Outfit', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv9: {
    name: 'Cobalt Pro Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#2563eb',
    secondary: '#38bdf8',
    sidebarBg: '#1e293b',
    sidebarText: '#f8fafc',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'accent-bullet',
  },
  Cv10: {
    name: 'Titanium Executive',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#334155',
    secondary: '#64748b',
    headerBg: '#1e293b',
    headerText: '#ffffff',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '4px',
    timelineStyle: 'subtle-line',
  },
  Cv11: {
    name: 'Prism Executive Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#4338ca',
    secondary: '#818cf8',
    headerBg: 'linear-gradient(135deg, #312e81 0%, #4338ca 100%)',
    headerText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv12: {
    name: 'Oxford Academic ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#18181b',
    secondary: '#71717a',
    font: "'Merriweather', serif",
    skillVariant: SKILL_VARIANTS.INLINE,
    dividerStyle: 'solid-thin',
    density: 'standard',
  },
  Cv13: {
    name: 'Cambridge Research',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#09090b',
    secondary: '#52525b',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    dividerStyle: 'solid-thin',
    density: 'standard',
  },
  Cv14: {
    name: 'Yale Corporate ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#1e293b',
    secondary: '#0284c7',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    dividerStyle: 'accent-left',
    density: 'standard',
  },
  Cv15: {
    name: 'MIT Technical ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#0f172a',
    secondary: '#059669',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    dividerStyle: 'accent-left',
    density: 'compact',
  },
  Cv16: {
    name: 'Apex Navy Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#1e3a8a',
    secondary: '#38bdf8',
    headerBg: 'linear-gradient(135deg, #172554 0%, #1e3a8a 100%)',
    headerText: '#ffffff',
    font: "'Outfit', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv17: {
    name: 'Teal Horizon Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#0f766e',
    secondary: '#14b8a6',
    headerBg: 'linear-gradient(135deg, #134e4a 0%, #0f766e 100%)',
    headerText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv18: {
    name: 'Princeton Minimal ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#27272a',
    secondary: '#52525b',
    font: "'Merriweather', serif",
    skillVariant: SKILL_VARIANTS.INLINE,
    dividerStyle: 'solid-thin',
    density: 'standard',
  },
  Cv19: {
    name: 'Zurich Financial ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#0f172a',
    secondary: '#3b82f6',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    dividerStyle: 'accent-left',
    density: 'compact',
  },
  Cv20: {
    name: 'Pacific Blue Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#0284c7',
    secondary: '#38bdf8',
    sidebarBg: '#f0f9ff',
    sidebarText: '#0369a1',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv21: {
    name: 'Imperial Indigo Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#3730a3',
    secondary: '#6366f1',
    headerBg: 'linear-gradient(135deg, #312e81 0%, #3730a3 100%)',
    headerText: '#ffffff',
    font: "'Outfit', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv22: {
    name: 'Geneva Executive ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#111827',
    secondary: '#4b5563',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    dividerStyle: 'solid-thin',
    density: 'standard',
  },
  Cv23: {
    name: 'Burgundy Prestige Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#881337',
    secondary: '#f43f5e',
    headerBg: 'linear-gradient(135deg, #4c0519 0%, #881337 100%)',
    headerText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv24: {
    name: 'Cyberpunk Modern Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#4f46e5',
    secondary: '#ec4899',
    sidebarBg: '#faf5ff',
    sidebarText: '#3b0764',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '35%',
    badgeRadius: '8px',
    timelineStyle: 'accent-bullet',
  },
  Cv25: {
    name: 'DevOps Terminal Tech',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#0f172a',
    secondary: '#10b981',
    sidebarBg: '#f8fafc',
    sidebarText: '#334155',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '34%',
    badgeRadius: '4px',
    timelineStyle: 'code-tag',
  },
  Cv26: {
    name: 'FullStack Dark Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#0284c7',
    secondary: '#38bdf8',
    sidebarBg: '#0f172a',
    sidebarText: '#f8fafc',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv27: {
    name: 'Creative Studio Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#d97706',
    secondary: '#fbbf24',
    sidebarBg: '#fffbeb',
    sidebarText: '#78350f',
    font: "'Outfit', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'accent-bullet',
  },
  Cv28: {
    name: 'Silicon Valley Engineer',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#2563eb',
    secondary: '#60a5fa',
    sidebarBg: '#f8fafc',
    sidebarText: '#1e293b',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv29: {
    name: 'Minimal Nordic Slate',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#334155',
    secondary: '#64748b',
    sidebarBg: '#f1f5f9',
    sidebarText: '#0f172a',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '33%',
    badgeRadius: '4px',
    timelineStyle: 'subtle-line',
  },
  Cv30: {
    name: 'Corporate Summit Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#1e293b',
    secondary: '#f59e0b',
    headerBg: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    headerText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv31: {
    name: 'Cloud Native Tech',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#0284c7',
    secondary: '#0ea5e9',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    badgeRadius: '6px',
    timelineStyle: 'code-tag',
  },
  Cv32: {
    name: 'Kubernetes Developer',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#326ce5',
    secondary: '#60a5fa',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv33: {
    name: 'Data Science Matrix',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#059669',
    secondary: '#34d399',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    badgeRadius: '6px',
    timelineStyle: 'code-tag',
  },
  Cv34: {
    name: 'Fintech Executive',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#0f172a',
    secondary: '#38bdf8',
    headerBg: '#0f172a',
    headerText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv35: {
    name: 'AI & ML Researcher',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#7c3aed',
    secondary: '#a78bfa',
    font: "'Outfit', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv36: {
    name: 'BioTech Specialist',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#0d9488',
    secondary: '#2dd4bf',
    headerBg: 'linear-gradient(135deg, #115e59 0%, #0d9488 100%)',
    headerText: '#ffffff',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv37: {
    name: 'Solutions Architect',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#ea580c',
    secondary: '#fb923c',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    badgeRadius: '6px',
    timelineStyle: 'code-tag',
  },
  Cv38: {
    name: 'Global Legal ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#18181b',
    secondary: '#71717a',
    font: "'Merriweather', serif",
    skillVariant: SKILL_VARIANTS.INLINE,
    dividerStyle: 'solid-thin',
    density: 'standard',
  },
  Cv39: {
    name: 'Product Manager Pro',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#2563eb',
    secondary: '#38bdf8',
    sidebarBg: '#f8fafc',
    sidebarText: '#1e293b',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv40: {
    name: 'Europass Classic Grid',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#003399',
    secondary: '#4169e1',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '4px',
  },
  Cv41: {
    name: 'Europass Modern Slate',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#1e293b',
    secondary: '#3b82f6',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    badgeRadius: '4px',
  },
  Cv42: {
    name: 'European Academic Compact',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#1e3a8a',
    secondary: '#60a5fa',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '4px',
  },
  Cv43: {
    name: 'Brussels International',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#0f766e',
    secondary: '#14b8a6',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    badgeRadius: '4px',
  },
  Cv44: {
    name: 'Scandinavia Clean Compact',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#0f172a',
    secondary: '#64748b',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    dividerStyle: 'solid-thin',
    density: 'compact',
  },
  Cv45: {
    name: 'Vienna Diplomatic Euro',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#881337',
    secondary: '#e11d48',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '4px',
  },
  Cv46: {
    name: 'Frankfurt Finance Euro',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#1e293b',
    secondary: '#0284c7',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    badgeRadius: '4px',
  },
  Cv47: {
    name: 'Metro Dual Column Pro',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#0369a1',
    secondary: '#38bdf8',
    sidebarBg: '#f0f9ff',
    sidebarText: '#0c4a6e',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv48: {
    name: 'Modern Gradient Aurora',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#6366f1',
    secondary: '#ec4899',
    sidebarBg: 'linear-gradient(180deg, #312e81 0%, #1e1b4b 100%)',
    sidebarText: '#f8fafc',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '35%',
    badgeRadius: '8px',
    timelineStyle: 'accent-bullet',
  },
  Cv49: {
    name: 'Berlin Tech Compact',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#18181b',
    secondary: '#3b82f6',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '4px',
  },
  Cv50: {
    name: 'Executive Platinum Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#0f172a',
    secondary: '#475569',
    sidebarBg: '#f8fafc',
    sidebarText: '#1e293b',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
  },
  Cv51: {
    name: 'Standard Europass Official',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#003399',
    secondary: '#4169e1',
    font: "Arial, 'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '3px',
  },
};

export function getThemePreset(templateId = 'Cv1') {
  return THEME_PRESETS[templateId] || THEME_PRESETS.Cv1;
}
