/**
 * Smart Hybrid Resume Engine — Theme & Design Token Presets
 * 
 * Maps all 51 template IDs (Cv1 to Cv51) into curated, enterprise-grade,
 * purposefully differentiated design configurations with unique archetypes,
 * distinct typography, harmonious color palettes, and specialized styling.
 */

export const ARCHETYPES = {
  MODERN_SPLIT: 'modern-split',         // Left sidebar (32-35%), crisp main flow (65-68%)
  EXECUTIVE_BANNER: 'executive-banner', // Full-width header banner, structured 2-col below
  MINIMAL_ATS: 'minimal-ats',           // Single column, 100% ATS-optimized, classic elegance
  TECH_GRID: 'tech-grid',               // Tech badges, repository links, compact timeline
  COMPACT_EURO: 'compact-euro',         // Europass / Academic timeline with date gutter
};

export const SKILL_VARIANTS = {
  PILLS: 'pills',                       // Compact multi-column pill wrap (best for 10+ skills)
  BADGES: 'badges',                     // Outlined tech tags with subtle background
  BARS: 'bars',                         // Horizontal proficiency meters
  DOTS: 'dots',                         // 5-dot rating indicator
  INLINE: 'inline',                     // Inline comma / bullet separated list
};

/**
 * 51 Curated, Visually Differentiated Theme Presets
 */
export const THEME_PRESETS = {
  // ── Modern Split Presets (Cv1, Cv2, Cv3, Cv7, Cv9, Cv20, Cv24, Cv26, Cv27, Cv29, Cv39, Cv47, Cv48, Cv50, Cv51) ──

  Cv1: {
    name: 'Metropolitan Navy',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#1e3a8a',
    secondary: '#3b82f6',
    sidebarBg: '#f8fafc',
    sidebarText: '#1e293b',
    headerBg: 'transparent',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
    headerStyle: 'sidebar',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  Cv2: {
    name: 'Nordic Slate',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#0f172a',
    secondary: '#0ea5e9',
    sidebarBg: '#f1f5f9',
    sidebarText: '#334155',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '33%',
    badgeRadius: '4px',
    timelineStyle: 'subtle-line',
    headerStyle: 'sidebar',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  Cv3: {
    name: 'Emerald Executive',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#065f46',
    secondary: '#10b981',
    sidebarBg: '#f0fdf4',
    sidebarText: '#166534',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
    headerStyle: 'sidebar',
    dividerStyle: 'left-bar',
    density: 'standard',
  },

  // ── Minimal ATS Presets (Cv4, Cv5, Cv6, Cv12, Cv13, Cv14, Cv15, Cv18, Cv19, Cv22, Cv38, Cv44) ──

  Cv4: {
    name: 'Harvard Classic ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#111827',
    secondary: '#4b5563',
    font: "'Merriweather', Georgia, serif",
    skillVariant: SKILL_VARIANTS.INLINE,
    headerStyle: 'centered-classic',
    dividerStyle: 'solid-thin',
    timelineStyle: 'compact-clean',
    density: 'standard',
  },

  Cv5: {
    name: 'Stanford Clean ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#1e293b',
    secondary: '#0ea5e9',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    headerStyle: 'left-bold',
    dividerStyle: 'left-bar',
    timelineStyle: 'modern-node',
    density: 'standard',
  },

  Cv6: {
    name: 'Wall Street Modern',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#0f172a',
    secondary: '#2563eb',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    headerStyle: 'minimal-inline',
    dividerStyle: 'double-line',
    timelineStyle: 'compact-clean',
    density: 'compact',
  },

  Cv7: {
    name: 'Sapphire Modern Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#1d4ed8',
    secondary: '#60a5fa',
    sidebarBg: '#eff6ff',
    sidebarText: '#1e3a8a',
    font: "'Montserrat', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '8px',
    timelineStyle: 'modern-node',
    headerStyle: 'sidebar',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  // ── Executive Banner Presets (Cv8, Cv10, Cv11, Cv16, Cv17, Cv21, Cv23, Cv30, Cv34, Cv36) ──

  Cv8: {
    name: 'Crown Executive Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#1e293b',
    secondary: '#3b82f6',
    headerBg: 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)',
    headerText: '#ffffff',
    font: "'Outfit', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
    headerStyle: 'banner',
    dividerStyle: 'solid-thin',
    density: 'spacious',
  },

  Cv9: {
    name: 'Cobalt Pro Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#2563eb',
    secondary: '#38bdf8',
    sidebarBg: '#1e293b',
    sidebarText: '#f8fafc',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'accent-bullet',
    headerStyle: 'sidebar',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  Cv10: {
    name: 'Titanium Executive',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#334155',
    secondary: '#64748b',
    headerBg: '#1e293b',
    headerText: '#ffffff',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '4px',
    timelineStyle: 'subtle-line',
    headerStyle: 'banner',
    dividerStyle: 'left-bar',
    density: 'compact',
  },

  Cv11: {
    name: 'Prism Executive Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#4338ca',
    secondary: '#818cf8',
    headerBg: 'linear-gradient(135deg, #312e81 0%, #4338ca 100%)',
    headerText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
    headerStyle: 'banner',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  Cv12: {
    name: 'Oxford Academic ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#1e1b4b',
    secondary: '#4338ca',
    font: "'Merriweather', serif",
    skillVariant: SKILL_VARIANTS.INLINE,
    headerStyle: 'centered-classic',
    dividerStyle: 'double-line',
    timelineStyle: 'compact-clean',
    density: 'standard',
  },

  Cv13: {
    name: 'Cambridge Research',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#09090b',
    secondary: '#52525b',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    headerStyle: 'minimal-inline',
    dividerStyle: 'solid-thin',
    timelineStyle: 'subtle-line',
    density: 'standard',
  },

  Cv14: {
    name: 'Yale Corporate ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#0c2340',
    secondary: '#c59b27',
    font: "'Cinzel', 'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    headerStyle: 'left-bold',
    dividerStyle: 'solid-thick',
    timelineStyle: 'modern-node',
    density: 'standard',
  },

  Cv15: {
    name: 'MIT Technical ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#8b0000',
    secondary: '#475569',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    headerStyle: 'accent-bracket',
    dividerStyle: 'left-bar',
    timelineStyle: 'code-tag',
    density: 'compact',
  },

  Cv16: {
    name: 'Apex Navy Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#1e3a8a',
    secondary: '#38bdf8',
    headerBg: 'linear-gradient(135deg, #172554 0%, #1e3a8a 100%)',
    headerText: '#ffffff',
    font: "'Outfit', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '31%',
    badgeRadius: '6px',
    timelineStyle: 'accent-bullet',
    headerStyle: 'banner',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  Cv17: {
    name: 'Teal Horizon Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#0f766e',
    secondary: '#14b8a6',
    headerBg: 'linear-gradient(135deg, #134e4a 0%, #0f766e 100%)',
    headerText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BARS,
    sidebarWidth: '33%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
    headerStyle: 'banner',
    dividerStyle: 'left-bar',
    density: 'standard',
  },

  Cv18: {
    name: 'Princeton Minimal ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#27272a',
    secondary: '#d97706',
    font: "'Georgia', serif",
    skillVariant: SKILL_VARIANTS.INLINE,
    headerStyle: 'centered-classic',
    dividerStyle: 'solid-thin',
    timelineStyle: 'compact-clean',
    density: 'standard',
  },

  Cv19: {
    name: 'Zurich Financial ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#004b49',
    secondary: '#d97706',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    headerStyle: 'centered-classic',
    dividerStyle: 'double-line',
    timelineStyle: 'compact-clean',
    density: 'compact',
  },

  Cv20: {
    name: 'Pacific Blue Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#0284c7',
    secondary: '#38bdf8',
    sidebarBg: '#f0f9ff',
    sidebarText: '#0369a1',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BARS,
    sidebarWidth: '34%',
    badgeRadius: '10px',
    timelineStyle: 'accent-bullet',
    headerStyle: 'sidebar',
    dividerStyle: 'solid-thick',
    density: 'standard',
  },

  Cv21: {
    name: 'Imperial Indigo Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#3730a3',
    secondary: '#6366f1',
    headerBg: 'linear-gradient(135deg, #312e81 0%, #3730a3 100%)',
    headerText: '#ffffff',
    font: "'Outfit', sans-serif",
    skillVariant: SKILL_VARIANTS.DOTS,
    sidebarWidth: '32%',
    badgeRadius: '6px',
    timelineStyle: 'subtle-line',
    headerStyle: 'banner',
    dividerStyle: 'double-line',
    density: 'standard',
  },

  Cv22: {
    name: 'Geneva Executive ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#18181b',
    secondary: '#dc2626',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    headerStyle: 'left-bold',
    dividerStyle: 'solid-thick',
    timelineStyle: 'compact-clean',
    density: 'compact',
  },

  Cv23: {
    name: 'Burgundy Prestige Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#881337',
    secondary: '#f43f5e',
    headerBg: 'linear-gradient(135deg, #4c0519 0%, #881337 100%)',
    headerText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '36%',
    badgeRadius: '6px',
    timelineStyle: 'compact-clean',
    headerStyle: 'banner',
    dividerStyle: 'solid-thick',
    density: 'spacious',
  },

  Cv24: {
    name: 'Cyberpunk Modern Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#4f46e5',
    secondary: '#ec4899',
    sidebarBg: '#faf5ff',
    sidebarText: '#3b0764',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '35%',
    badgeRadius: '8px',
    timelineStyle: 'code-tag',
    headerStyle: 'sidebar',
    dividerStyle: 'solid-thin',
    density: 'compact',
  },

  // ── Tech Grid Presets (Cv25, Cv28, Cv31, Cv32, Cv33, Cv35, Cv37) ──

  Cv25: {
    name: 'DevOps Terminal Tech',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#0f172a',
    secondary: '#10b981',
    sidebarBg: '#f8fafc',
    sidebarText: '#334155',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '34%',
    badgeRadius: '4px',
    timelineStyle: 'code-tag',
    headerStyle: 'left-bold',
    dividerStyle: 'left-bar',
    density: 'standard',
  },

  Cv26: {
    name: 'FullStack Dark Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#0891b2',
    secondary: '#06b6d4',
    sidebarBg: '#090d16',
    sidebarText: '#f8fafc',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'code-tag',
    headerStyle: 'sidebar',
    dividerStyle: 'left-bar',
    density: 'compact',
  },

  Cv27: {
    name: 'Creative Studio Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#d97706',
    secondary: '#fbbf24',
    sidebarBg: '#fffbeb',
    sidebarText: '#78350f',
    font: "'Outfit', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'accent-bullet',
    headerStyle: 'sidebar',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  Cv28: {
    name: 'Silicon Valley Engineer',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#2563eb',
    secondary: '#60a5fa',
    sidebarBg: '#f8fafc',
    sidebarText: '#1e293b',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '34%',
    badgeRadius: '3px',
    timelineStyle: 'code-tag',
    headerStyle: 'left-bold',
    dividerStyle: 'left-bar',
    density: 'compact',
  },

  Cv29: {
    name: 'Minimal Nordic Slate',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#334155',
    secondary: '#64748b',
    sidebarBg: '#f1f5f9',
    sidebarText: '#0f172a',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.INLINE,
    sidebarWidth: '33%',
    badgeRadius: '4px',
    timelineStyle: 'compact-clean',
    headerStyle: 'sidebar',
    dividerStyle: 'double-line',
    density: 'spacious',
  },

  Cv30: {
    name: 'Corporate Summit Banner',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#b45309',
    secondary: '#f59e0b',
    headerBg: 'linear-gradient(135deg, #78350f 0%, #b45309 100%)',
    headerText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.INLINE,
    sidebarWidth: '30%',
    badgeRadius: '6px',
    timelineStyle: 'subtle-line',
    headerStyle: 'banner',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  Cv31: {
    name: 'Cloud Native Tech',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#0891b2',
    secondary: '#0ea5e9',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.DOTS,
    badgeRadius: '6px',
    timelineStyle: 'code-tag',
    headerStyle: 'left-bold',
    dividerStyle: 'left-bar',
    density: 'spacious',
  },

  Cv32: {
    name: 'Kubernetes Developer',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#326ce5',
    secondary: '#60a5fa',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '6px',
    timelineStyle: 'code-tag',
    headerStyle: 'left-bold',
    dividerStyle: 'double-line',
    density: 'standard',
  },

  Cv33: {
    name: 'Data Science Matrix',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#059669',
    secondary: '#34d399',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BARS,
    badgeRadius: '8px',
    timelineStyle: 'code-tag',
    headerStyle: 'left-bold',
    dividerStyle: 'double-line',
    density: 'compact',
    sidebarWidth: '30%',
  },

  Cv34: {
    name: 'Fintech Executive',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#0b0f19',
    secondary: '#00e5ff',
    headerBg: 'linear-gradient(135deg, #0b0f19 0%, #1e293b 100%)',
    headerText: '#ffffff',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.DOTS,
    sidebarWidth: '38%',
    badgeRadius: '2px',
    timelineStyle: 'code-tag',
    headerStyle: 'banner',
    dividerStyle: 'double-line',
    density: 'standard',
  },

  Cv35: {
    name: 'AI & ML Researcher',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#7c3aed',
    secondary: '#a78bfa',
    font: "'Outfit', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    badgeRadius: '6px',
    timelineStyle: 'code-tag',
    headerStyle: 'left-bold',
    dividerStyle: 'double-line',
    density: 'compact',
  },

  Cv36: {
    name: 'BioTech Specialist',
    archetype: ARCHETYPES.EXECUTIVE_BANNER,
    primary: '#0d9488',
    secondary: '#2dd4bf',
    headerBg: 'linear-gradient(135deg, #115e59 0%, #0d9488 100%)',
    headerText: '#ffffff',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '35%',
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
    headerStyle: 'banner',
    dividerStyle: 'double-line',
    density: 'spacious',
  },

  Cv37: {
    name: 'Solutions Architect',
    archetype: ARCHETYPES.TECH_GRID,
    primary: '#ea580c',
    secondary: '#fb923c',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BARS,
    badgeRadius: '6px',
    timelineStyle: 'modern-node',
    headerStyle: 'left-bold',
    dividerStyle: 'solid-thick',
    density: 'standard',
    sidebarWidth: '36%',
  },

  Cv38: {
    name: 'Global Legal ATS',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#0f172a',
    secondary: '#0284c7',
    font: "'Georgia', serif",
    skillVariant: SKILL_VARIANTS.INLINE,
    headerStyle: 'accent-bracket',
    dividerStyle: 'left-bar',
    timelineStyle: 'compact-clean',
    density: 'standard',
  },

  Cv39: {
    name: 'Product Manager Pro',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#4338ca',
    secondary: '#f59e0b',
    sidebarBg: '#fafafa',
    sidebarText: '#1e293b',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '34%',
    badgeRadius: '6px',
    timelineStyle: 'accent-bullet',
    headerStyle: 'sidebar',
    dividerStyle: 'left-bar',
    density: 'spacious',
  },

  // ── Compact Euro Presets (Cv40, Cv41, Cv42, Cv43, Cv45, Cv46, Cv49) ──

  Cv40: {
    name: 'Europass Classic Grid',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#003399',
    secondary: '#4169e1',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '4px',
    timelineStyle: 'date-rail',
    headerStyle: 'minimal-inline',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  Cv41: {
    name: 'Europass Modern Slate',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#1e293b',
    secondary: '#3b82f6',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.DOTS,
    badgeRadius: '4px',
    timelineStyle: 'date-rail',
    headerStyle: 'left-bold',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  Cv42: {
    name: 'European Academic Compact',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#1e3a8a',
    secondary: '#60a5fa',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '4px',
    timelineStyle: 'date-rail',
    headerStyle: 'centered-classic',
    dividerStyle: 'double-line',
    density: 'standard',
  },

  Cv43: {
    name: 'Brussels International',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#0f766e',
    secondary: '#14b8a6',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    badgeRadius: '4px',
    timelineStyle: 'date-rail',
    headerStyle: 'left-bold',
    dividerStyle: 'double-line',
    density: 'spacious',
  },

  Cv44: {
    name: 'Scandinavia Clean Compact',
    archetype: ARCHETYPES.MINIMAL_ATS,
    primary: '#334155',
    secondary: '#10b981',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.DOTS,
    headerStyle: 'minimal-inline',
    dividerStyle: 'solid-thin',
    timelineStyle: 'compact-clean',
    density: 'compact',
  },

  Cv45: {
    name: 'Vienna Diplomatic Euro',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#881337',
    secondary: '#e11d48',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '4px',
    timelineStyle: 'date-rail',
    headerStyle: 'left-bold',
    dividerStyle: 'solid-thick',
    density: 'standard',
  },

  Cv46: {
    name: 'Frankfurt Finance Euro',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#1e3a8a',
    secondary: '#0284c7',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    badgeRadius: '4px',
    timelineStyle: 'date-rail',
    headerStyle: 'left-bold',
    dividerStyle: 'left-bar',
    density: 'standard',
  },

  Cv47: {
    name: 'Metro Dual Column Pro',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#0369a1',
    secondary: '#38bdf8',
    sidebarBg: '#f0f9ff',
    sidebarText: '#0c4a6e',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    sidebarWidth: '37%',
    badgeRadius: '6px',
    timelineStyle: 'subtle-line',
    headerStyle: 'sidebar',
    dividerStyle: 'solid-thin',
    density: 'compact',
  },

  Cv48: {
    name: 'Modern Gradient Aurora',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#6366f1',
    secondary: '#ec4899',
    sidebarBg: 'linear-gradient(180deg, #312e81 0%, #1e1b4b 100%)',
    sidebarText: '#f8fafc',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.DOTS,
    sidebarWidth: '35%',
    badgeRadius: '8px',
    timelineStyle: 'modern-node',
    headerStyle: 'sidebar',
    dividerStyle: 'solid-thick',
    density: 'spacious',
  },

  Cv49: {
    name: 'Berlin Tech Compact',
    archetype: ARCHETYPES.COMPACT_EURO,
    primary: '#18181b',
    secondary: '#3b82f6',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.PILLS,
    badgeRadius: '4px',
    timelineStyle: 'date-rail',
    headerStyle: 'minimal-inline',
    dividerStyle: 'left-bar',
    density: 'compact',
  },

  // ── Reverse Split & Specialized Formats (Cv50, Cv51) ──

  Cv50: {
    name: 'Executive Platinum Split',
    archetype: ARCHETYPES.MODERN_SPLIT,
    sidebarPosition: 'right', // Unique Right-Sidebar Split!
    primary: '#0f172a',
    secondary: '#475569',
    sidebarBg: '#e2e8f0',
    sidebarText: '#1e293b',
    font: "'Plus Jakarta Sans', sans-serif",
    skillVariant: SKILL_VARIANTS.BADGES,
    sidebarWidth: '32%',
    badgeRadius: '6px',
    timelineStyle: 'subtle-line',
    headerStyle: 'sidebar',
    dividerStyle: 'solid-thin',
    density: 'standard',
  },

  Cv51: {
    name: 'Standard Europass Modern',
    archetype: ARCHETYPES.MODERN_SPLIT,
    primary: '#0f4c81',
    secondary: '#f59e0b',
    sidebarBg: '#eff6ff',
    sidebarText: '#1e3a8a',
    font: "'Inter', sans-serif",
    skillVariant: SKILL_VARIANTS.DOTS,
    sidebarWidth: '33%',
    badgeRadius: '4px',
    timelineStyle: 'date-rail',
    headerStyle: 'sidebar',
    dividerStyle: 'left-bar',
    density: 'standard',
  },
};

export function getThemePreset(templateId = 'Cv1') {
  return THEME_PRESETS[templateId] || THEME_PRESETS.Cv1;
}
